# Generated by Django 5.2 on 2025-04-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default-background/defalut-background.jpeg', null=True, upload_to='post_images'),
        ),
    ]
