# Generated by Django 5.2 on 2025-11-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_send_failed',
            field=models.BooleanField(default=False),
        ),
    ]
